namespace Common.Enums.ErrorEnums
{
    public enum ErrorCodes
    {
        // from Invoice Project (0 - 100)
        SUCCESS = 0,
        INTERNAL_ERROR = 1,
        UNAUTHORIZED = 2,
        USER_DOES_NOT_EXIST = 3,
        LOGIN_AND_PASSWORD_DOESNT_MATCH = 4,
        PERMISSION_DOES_NOT_EXIST = 5,
        ROLE_DOES_NOT_EXIST = 6,
        INPUT_IS_NOT_VALID = 7,
        TOKEN_DOES_NOT_EXIST = 8,
        SAME_PASSWORD = 9,
        INCORRECT_PASSWORD = 10,
        EMAIL_IS_NOT_VALID = 11,
        PASSWORDS_MUST_BE_SAME = 12,
        INCORRECT_OR_EXPIRED_OTP_CODE = 13,
        ACCOUNT_DOES_NOT_EXIST = 14,
        INSUFFICIENT_FUNDS = 15,
        ACCESS_DENIED = 16,
        PAYER_ACCOUNT_DOES_NOT_EXIST = 17,
        INVOICE_ACCOUNT_DOES_NOT_EXIST = 18,


        // this project Payment (101 - 200)
        INVOICE_DOES_NOT_EXIST = 101,
        PAYMENT_DOES_NOT_EXIST = 102,
        PAYMENT_MUST_BE_UNIQUE = 103,
        INVOICE_PAID_OUT = 104,
        INVALID_MIN_TRANSACTION = 105,
        INVALID_MAX_TRANSACTION = 106,
        INVOICE_EXPIRED = 107,
        INVALID_MONTHLY_SUM = 108,
        INVALID_MONTHLY_LIMIT = 109,
        SUM_MORE_THAN_INVOICE_SUM = 110,
        PAYMENT_DOES_NOT_PAYED = 111,
        PAYMENT_WAS_EXPIRED = 112,
        ORGANIZATION_DOES_NOT_EXIST = 113,
        APPLICATION_DOES_NOT_EXISTS = 114,
        MERCHANT_SETTING_DOES_NOT_EXISTS = 115,
        IPADDRESS_IS_NOT_ALLOWED=116 ,


        SIGNATURE_IS_NOT_VALID=117

    }
}
